name: blake2b
description: A dart implement of blake2b referenced from blacknet.
version: 0.2.2
homepage: https://github.com/riclava/blake2b

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter